application: bangkok-is
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: index.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(.+)
  script: \1.php
